web: python manage.py runserver
flow_worker_1: celery -A whatsappcrm_backend worker -Q flow -l info --concurrency=1 --hostname=flow1@%h
flow_worker_2: celery -A whatsappcrm_backend worker -Q flow -l info --concurrency=1 --hostname=flow2@%h
message_worker: celery -A whatsappcrm_backend worker -Q message_sending -l info --concurrency=2 --hostname=msg@%h
default_worker: celery -A whatsappcrm_backend worker -Q celery,cpu_heavy -l info --concurrency=1 --hostname=default@%h
beat: celery -A whatsappcrm_backend beat -l info
flower: celery -A whatsappcrm_backend flower --port=5558