# Generated by Django 5.0.7 on 2025-11-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tour Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('safari', 'Safari'), ('cultural', 'Cultural Tour'), ('adventure', 'Adventure & Sports'), ('city', 'City Tour'), ('custom', 'Custom Package')], default='safari', max_length=20, verbose_name='Category')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per adult.', max_digits=10, verbose_name='Base Price')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duration in Days')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Region')),
                ('image', models.ImageField(blank=True, help_text='A representative image for the tour.', null=True, upload_to='tours/', verbose_name='Tour Image')),
                ('is_active', models.BooleanField(default=True, help_text='Is this tour currently available for booking?', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['name'],
            },
        ),
    ]
