# Generated by Django 5.2.9 on 2025-12-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the pricing period', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='End date of the pricing period', verbose_name='End Date')),
                ('price_per_adult', models.DecimalField(decimal_places=2, help_text='Price per adult for this period', max_digits=10, verbose_name='Price Per Adult')),
                ('price_per_child', models.DecimalField(blank=True, decimal_places=2, help_text='Price per child for this period (optional, defaults to adult price)', max_digits=10, null=True, verbose_name='Price Per Child')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='products_and_services.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Seasonal Tour Price',
                'verbose_name_plural': 'Seasonal Tour Prices',
                'ordering': ['tour', 'start_date'],
            },
        ),
    ]
