# Generated by Django 5.2.9 on 2025-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0002_seasonaltourprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', help_text='Unit of time for the duration', max_length=10, verbose_name='Duration Unit'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text='Numeric value for the duration (e.g., 2, 30, 1)', verbose_name='Duration Value'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Deprecated: Use duration_value and duration_unit instead. This field is kept for backward compatibility.', verbose_name='Duration in Days'),
        ),
    ]
