# Generated by Django 5.2.9 on 2025-12-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0003_tour_duration_unit_tour_duration_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes')], default='days', help_text='Unit of time for the duration', max_length=10, verbose_name='Duration Unit'),
        ),
    ]
