# Generated by Django 5.2.9 on 2025-12-21 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_data', '0006_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmariConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Configuration name for reference', max_length=100)),
                ('base_url', models.URLField(help_text='Base URL for Omari Merchant API (e.g., https://omari.v.co.zw/uat/vsuite/omari/api/merchant/api/payment)', max_length=500)),
                ('merchant_key', models.CharField(help_text="API Key provided by Omari for merchant authentication", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('is_production', models.BooleanField(default=False, help_text='Indicates if this configuration is for production or testing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Omari Configuration',
                'verbose_name_plural': 'Omari Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmariTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('msisdn', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWG', 'ZWG')], max_length=3)),
                ('channel', models.CharField(choices=[('WEB', 'WEB'), ('POS', 'POS')], default='WEB', max_length=10)),
                ('otp_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('otp_requested_at', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('OTP_SENT', 'OTP Sent'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='INITIATED', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='The booking this payment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omari_transactions', to='customer_data.booking')),
            ],
            options={
                'verbose_name': 'Omari Transaction',
                'verbose_name_plural': 'Omari Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
