# Generated by Django 5.2.9 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omari_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmariUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Omari User',
                'verbose_name_plural': 'Omari Users',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='omaritransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('OTP_SENT', 'OTP Sent'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('VOIDED', 'Voided')], default='INITIATED', max_length=20),
        ),
    ]
