# Generated by Django 5.2.9 on 2026-02-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omari_integration', '0002_omariuser'),
        ('omari_integration', '0002_omariuser_alter_omaritransaction_status'),
    ]

    operations = [
    ]
