# Generated by Django 5.0.7 on 2025-11-29 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_contact_associated_app_config_and_more'),
        ('flows', '0003_flow_friendly_name_flow_trigger_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for this template, e.g., 'human_handover_required'.", max_length=100, unique=True, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', help_text='The type of channel this template is designed for (e.g., WhatsApp, Email).', max_length=20, verbose_name='Template Type')),
                ('message_body', models.TextField(help_text='The template content. Can use Jinja2 variables like {{ contact.name }}.', verbose_name='Message Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='whatsapp', max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('content', models.TextField(verbose_name='Content')),
                ('template_name', models.CharField(blank=True, help_text='The name of the WhatsApp template to use if outside the 24h window.', max_length=100, null=True)),
                ('template_context', models.JSONField(blank=True, help_text='The context data required to render the template variables.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='conversations.contact')),
                ('related_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='flows.flow')),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
