# Generated by Django 5.0.7 on 2025-11-29 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Date')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='Messages Sent')),
                ('messages_received', models.PositiveIntegerField(default=0, verbose_name='Messages Received')),
                ('new_contacts', models.PositiveIntegerField(default=0, verbose_name='New Contacts')),
                ('new_bookings_count', models.PositiveIntegerField(default=0, verbose_name='New Bookings Count')),
                ('paid_bookings_count', models.PositiveIntegerField(default=0, verbose_name='Paid Bookings Count')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Revenue from Won Orders')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
    ]
