# Generated by Django 5.0.7 on 2025-11-29 00:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_contact_associated_app_config_and_more'),
        ('customer_data', '0002_customerprofile_acquisition_source_and_more'),
        ('products_and_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-last_interaction_date', '-updated_at'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_updated_from_conversation',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='lifecycle_stage',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='secondary_phone_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The sales or support agent assigned to this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_interaction_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last recorded interaction with this customer.', null=True, verbose_name='Last Interaction Date'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0, help_text='A score to qualify leads, can be updated by flow actions.', verbose_name='Lead Score'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], db_index=True, default='new', help_text='The current stage of the customer in the sales pipeline.', max_length=50, verbose_name='Lead Status'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='potential_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value of the deal or lifetime value of the customer.', max_digits=12, null=True, verbose_name='Potential Value'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role/Title'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='acquisition_source',
            field=models.CharField(blank=True, help_text="How this customer was acquired, e.g., 'Website Form', 'Cold Call', 'Referral'", max_length=150, null=True, verbose_name='Acquisition Source'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='contact',
            field=models.OneToOneField(help_text='The contact this customer profile belongs to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to='conversations.contact'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible field for storing custom data collected via forms or integrations.'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the customer, their needs, or past interactions.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Descriptive tags for segmentation, e.g., ['high-priority', 'tech-industry', 'follow-up']", verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Booking Reference')),
                ('tour_name', models.CharField(help_text='Name of the tour at the time of booking', max_length=255, verbose_name='Tour Name')),
                ('start_date', models.DateField(verbose_name='Tour Start Date')),
                ('end_date', models.DateField(verbose_name='Tour End Date')),
                ('number_of_adults', models.PositiveIntegerField(default=1, verbose_name='Number of Adults')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='Number of Children')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('pending_manual', 'Pending Manual Verification'), ('deposit_paid', 'Deposit Paid'), ('paid', 'Paid in Full'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=50, verbose_name='Payment Status')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email_import', 'Email Import'), ('manual_entry', 'Manual Entry'), ('phone_call', 'Phone Call')], default='manual_entry', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('booking_details_payload', models.JSONField(blank=True, help_text='Raw structured data from an email or other source.', null=True, verbose_name='Booking Details Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customer_data.customerprofile')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='products_and_services.tour')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp Message'), ('meeting', 'Meeting'), ('note', 'Internal Note'), ('other', 'Other')], default='note', max_length=50, verbose_name='Interaction Type')),
                ('notes', models.TextField(help_text='A summary of the interaction, key points, and next steps.', verbose_name='Notes / Summary')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the interaction occurred.', verbose_name='Interaction Time')),
                ('agent', models.ForeignKey(blank=True, help_text='The agent who had the interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer this interaction is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customer_data.customerprofile')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('omari', 'Omari'), ('other', 'Other')], default='other', max_length=20, verbose_name='Payment Method')),
                ('transaction_reference', models.CharField(blank=True, help_text='A reference from the payment provider, e.g., transaction ID.', max_length=255, null=True, verbose_name='Transaction Reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customer_data.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('converted', 'Converted to Booking'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Inquiry Status')),
                ('lead_traveler_name', models.CharField(blank=True, max_length=255, verbose_name='Lead Traveler Name')),
                ('destinations', models.CharField(blank=True, max_length=255, verbose_name='Destinations of Interest')),
                ('preferred_dates', models.CharField(blank=True, max_length=255, verbose_name='Preferred Travel Dates')),
                ('number_of_travelers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Travelers')),
                ('notes', models.TextField(blank=True, verbose_name='Customer Notes / Requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_inquiries', to='customer_data.customerprofile')),
            ],
            options={
                'verbose_name': 'Tour Inquiry',
                'verbose_name_plural': 'Tour Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
