# Generated by Django 5.2.9 on 2025-12-09 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0003_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('id_number', models.CharField(max_length=50, verbose_name='ID/Passport Number')),
                ('medical_dietary_requirements', models.TextField(blank=True, help_text='Any special medical or dietary needs.', null=True, verbose_name='Medical/Dietary Requirements')),
                ('traveler_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10, verbose_name='Traveler Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The booking this traveler is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='customer_data.booking')),
            ],
            options={
                'verbose_name': 'Traveler',
                'verbose_name_plural': 'Travelers',
                'ordering': ['booking', 'traveler_type', 'name'],
            },
        ),
    ]
