# Generated by Django 5.2.9 on 2025-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0004_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourinquiry',
            name='inquiry_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Inquiry Reference'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Booking Reference'),
        ),
    ]
