# Generated by Django 5.2.9 on 2025-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0005_add_inquiry_reference_and_update_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Shared reference for same tour/date', max_length=100, verbose_name='Booking Reference'),
        ),
    ]
