# Generated by Django 5.2.9 on 2026-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0006_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload a photo or scan of ID/Passport', null=True, upload_to='traveler_documents/%Y/%m/', verbose_name='ID/Passport Document'),
        ),
    ]
