# Generated by Django 5.2.9 on 2026-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0007_add_id_document_to_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('omari', 'Omari'), ('paynow_ecocash', 'Paynow - Ecocash'), ('paynow_onemoney', 'Paynow - OneMoney'), ('paynow_innbucks', 'Paynow - Innbucks'), ('other', 'Other')], default='other', max_length=20, verbose_name='Payment Method'),
        ),
    ]
