# Generated by Django 5.2.17 on 2026-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_data", "0008_add_paynow_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="held_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("pending_manual", "Pending Manual Verification"),
                    ("deposit_paid", "Deposit Paid"),
                    ("paid", "Paid in Full"),
                    ("awaiting_details", "Paid - Awaiting Passenger Details"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                help_text="Status a payment tried to set while passenger details were incomplete; applied automatically once they are complete.",
                max_length=50,
                verbose_name="Held Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_manual", "Pending Manual Verification"),
                    ("deposit_paid", "Deposit Paid"),
                    ("paid", "Paid in Full"),
                    ("awaiting_details", "Paid - Awaiting Passenger Details"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=50,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("omari", "Omari"),
                    ("paynow_ecocash", "Paynow - Ecocash"),
                    ("paynow_onemoney", "Paynow - OneMoney"),
                    ("paynow_innbucks", "Paynow - Innbucks"),
                    ("cbz_ecocash", "CBZ - EcoCash"),
                    ("cbz_card", "CBZ - Card (Visa/Mastercard)"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
                verbose_name="Payment Method",
            ),
        ),
    ]
