# Generated by Django 5.2.17 on 2026-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_data", "0009_booking_awaiting_passenger_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="Required from age 12; optional for younger children.",
                max_length=50,
                verbose_name="ID/Passport Number",
            ),
        ),
    ]
